name: CI
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
jobs:
  test:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependency
        run: make mod
      - name: Unit test
        run: make test
        continue-on-error: false
  build:
    runs-on: [self-hosted, Linux]
    needs: [test]
    steps:
      - name: Login docker registries
        run:
          sudo docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Change script permission
        run: sudo chmod +x ./build_image.sh
      - name: Build
        run: sudo ./build_image.sh
  deploy:
    runs-on: [self-hosted, Linux]
    needs: [build]
    container:
      image: lhhoangit/bee-go-demo:latest
      env:
        UP_STAGE: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - uses: addnab/docker-run-action@v3
        with:
          image: bee-go-demo:latest
          run: echo "hello world"